---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-db-creds
  namespace: default
spec:
  encryptedData:
    password: AgAPj+oCvHVkoqtafiiXQXeHZ3elt1MOGm68udC0ZGH2Zkn+DUz9S1ycq6KTXkKMQqCKH28hSrGEKGNEz+jeenmw6GWROVNi7UGFAHHpJZKtJUcVmzRAFauAw+5jdfCXPb4paGc0uDsyE7g7wc83rSv+RVziA4r12mu0OAG4Khc+lClgZc94g9pxm/i2ZvQ7LomiAZgxu1nhd5aNAyHL4F5aV+v4aJFqQ1terxLbZrbFI/TTUsOF/4SOc0hKott01VgVyHhWB+Z671PRiJ72mowEyd9OglQ2Oq6mYy3A5fuz34+MadCpaFHhlh3dON3+C/tK83O0SQtoljMc1f3qOrIhj4D3ZI/4d5o/Q2aBAd1Bm89bhTKD2Oa7Yi8f600sCabag4lrQZLCiC+TZNE1zzh70VQNoLi2nFVCUiZnTK4NpPlPppT+Tc91c0OIL4vdfSkuTW3WH7E48Sze8BTx8VcqYWROXyfkIRnicGpXQ1BN5s0bcnHbK8ckuRrCIffIidKjR23xwXIri47sDIXIFQsm6JqoLo84FlwXrXm5er923HjnBp69ykmXZSdlc/kFOTp4AiJBbifT8RkKNRDQ68srRxPyHON/JQDk2g9HhqqIaQbtiW7tO1vj7krIh+xtCpnmpYImkh/FQOLkL5NIkfg6o26Yfa9pxCSDwdiWeKvLuLt2pSq4FOjeuMOv3Ryx2PeK98CRKCNBfw1apl7Nrivj
    username: AgClE2vW6JXS1/+/pNlwo0tU+Dxd4H6WR1yGOxorjVYN0r8XruSouSAveI0R6UHRtTZ7evU1nr3UJk+s9IsBIZvEnHDgU9a+hDv5eHUKlP8ItzuZ6vUUzheELJ+WCoaeCMyMRS3PHvjUaMyBirWIYeRygDNt3WpA4x64SZghyXlbqTlMYl6fS1/RGAZwobQWyTqQa3CXb79o2AIdvSyihPM1tFnR0zy9ymFm9ijtGf6xgdm+17THnDeXEBxRaVYDJREEYHDlBzXmyns75UqqXjW6nWIOeBqT0Pk287cnGVxCIAH0UgyUNk0BtQNRWktiy1DhIwzTNEpwiP+Z5A2w+4uqkddc38AWEKj75LXF7afCkBsOmm+zWCVxODjLEkSD1vZ6ClpCCdKge4ywud2OPylWazfjtSPYRuReW8LK2ZisI0NZfaC8feHUpnzRfT41NMG7jS9aXPj6lUuC9yGNg4nqEHNzHQLUHZgLnoH9xMayn0vSi4KmjdQuPcrPTkDvA9MgbTFcrkbUOProup+3A6HoEFq11YUxfktj2Z1FEeg7OR/KCWoVLjqxpjGJSNk+sOUc7QHNwKZEEVRrGc649lWRIg/UboTEKDL9MGx2Uax13VKH3zYnr7FDa8kulnQHNcP6iqI4wzGbOKMklxGnQTaT4NOSqEEuXYql8Llm5WIdclrod87acO3s2ebieUZbyuUb217kmPx2W+jhjw==
  template:
    metadata:
      name: vaultwarden-db-creds
      namespace: default
    type: kubernetes.io/basic-auth
