---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin-vars
  namespace: default
spec:
  encryptedData:
    ADMIN_TOKEN: AgAW/rjtbDyiSHIGwimq2pDbdYHhR/7D2W1zjlOaprEqLxno8hvJ60FCWMf1juMJXmaP+zro7IoR6iwt/vSOq6SKqfK5zH4AugiRY/g6MaT5Tmt1S+lJueNgQRTz5Y62VOTEL0IY5idxGVH/wx3sJTNOSD8hwGcJFOE8hoUchsm9b65eSIZ6V/dUcvqFEa18Uz63L+pMaM/wloUJTYCq/7/sdJN/BXB+iuwbw/BmPPMmRpAqhsZjCbwFY/wt+p/q+NYymefHCFSSKZ1+OPOMidTque+GTGtLNZrU9MR1qdaTAdxWSAQnatjNI/jF7DlK9utKYLyNgXWGzD18maM7ComtsLzaLzdNbHYgu8zpFrUH3Ba+8vOWIZ3fgtVJP/ol0KLiDWUpBtA17S3fKVpWqzrwUlSeTbgfDmwaEiqNXsHxNO+ZvZz5DOWNnoBKVmwfGyIinVUowMKcrqXLfNQeE/yBgpK2EdTbpSPEQf2wpFLTJbDkM5EbOvwIkpCbvDB35W5lXb65UJzr9RbpIywTFibUspDdaBKaV8UWsP/SzUkQPpiVSKQ8T+fx1EIuqw25Lszj70DqiS67f51Xmk866vg9qJJgJJ28BIB02fUlDwLSYk4Ex9Gh9vSsFkIxy92GhApr2BzK6kcIcWe5DjRPWp+aH054qjQNRE1/xEs8Z1WopjMIxkp3vPJgyHbZBKnLzAKSXfi0gTTNZZBn8PtZIcYC2k0/jwu0HLYLrZNU9skvyrHch49Mb6qJt82qLyF9/Q47PjuygNLbiY0OEO/3usbOwJ0nudApHKJSjaUOwUAYLu1L2ncvefpQWUhg2EXiuzByVRCnmFd6tSSfBitXigG8Qx+bmkjoMDsTTrXJWwOzrLMTLgRqmg==
  template:
    metadata:
      name: vaultwarden-admin-vars
      namespace: default
    type: Opaque
