---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-db-creds
  namespace: default
spec:
  encryptedData:
    password: AgAo9cmbp3TQiMyX6rrzXTMQcVt9aOIrrG/nInvWwBe38UhjlzqszQSGD9SgymKy0yxRhVQVlMszCtmFtiN4hOOh21Cnw2wEjq4xt+recKOpllxJHsKiaQC8sgMJu7LTWMuf0hC5uainrIlH3mfyFLczAGf7IHXdyBu6d7ph3udagV0mOoTVsK/As/S/BRsUyJ08oBNy2HmZC8cncbHyw6JmRCRQpO7Abe4erC/9tSfjrgDAzGiTIReoWqjZwp66+yRXMYDGFWKvrfWNk14vKZ7oboWWc2rGo2r5fn9WVzMRelalDnOJDHAj3h4xuiQC9PZmPrHGk+q3L1W8mzCI9P+0VoaAViKTR3DHKbhT13A2hkE35eAzCNRmq2MHue+AnMTxQQ2BPqXaVVO/aQ9UkfFi6HxMRM3aUBCTOa5AZ9/Dn7SMDS6r1aid5HIytX3/PfVG9mO5AILYpjxrGwNTw6dcJMnhwUIuqMpAAzp+IMTZz3mo+H8JUIc0J/qeveyzG10P+7S/nd0LMiI8EK4RwrkzZC4mXYeB2R09rFOfSxToTFdSaNF1kH9fUd+Gnw0MWynaRYT6IgXpt2b+vdLiJ60+5kpriHW7hJEHVhDw5KvPjZnQLslbxWPZIuFTuyS1B1POUmzIbXrdPFri0r5KmtD0c30fv586LBtxuaZGOg2lcMmyu1BkYLB8aCdM6ZAW14V/K5wxMgKMJ9ghQOdloPwW
    username: AgDvI+W+5oHKUcwbRmrj02JI16ZmDmfm8b9m1RgqZwn1Hvh713GzvtsRWnqGz7NqwLaaopnTzN/SVhK3AQP9Np8M/7kLDbO6eQehzXZjgyjYC7m7cDuf9HuvcVKAgWH7eE0sXA8DrvgLZa+Cb17oLxS3P6J8cU7Hxik1FBJrhv61lJkRCH6RV+Xm9SxqRy8maWYmK1HwEK/geh4nI9S8CgO5HSz9t0+6wnn7OdxERB8Lb3fcf7TjpszxTaDoRtSrgCjc+IUAaN8Y6NCxQcqW+okt6wyxT9XspyCThp5ZKSQKU7au8xE0D1Y9Is5G8ZdwTzHE7r8yg0DJiPRxJ3n+0aMc7Zaw36KdmCT8smt8+dEmP48NUY/tcm3YC58djhRcE9Tun1ALjKcq68k8qrmWy/Kmhv+aSq5sncGgslHVJzBRiMHy9i2xxREdNDsCO9weec+ch2rYJlbu1siSaZm+YUt3uWjQxQObO8HVMmlEYdPK0rGYGEXW2Ts1vgHsPRsMN+X4sE4I2bpw4C+DMebBGn/+C5DT495CEa2HWgME0RU84JYn6vUhC5e2LTJ66z+ScrnIQUL5DykI/w6B9w+t5kkdzULdi4M2s+9yHfDWqzzSWmsi3x2KGRc30oSzk2CX0LM99lv9aY/1eMCBg2lF+bCXVWa5OLcX66kvTMbmztraXDYX8AEWePnJp1Oa5NIc+l+r5ikjsOlJxEhi1Q==
  template:
    metadata:
      name: vaultwarden-db-creds
      namespace: default
    type: kubernetes.io/basic-auth
