---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db-creds
  namespace: default
spec:
  encryptedData:
    password: AgBSnOubjaEp7Mc3k+NeaPQ8XgyhknQuTgxG8Gc2em6lpmW5A6wsofnuqQo9yzw7tIReJfWjiNsFMOrY3vEOZQ9JVZwtaMIPeg3NbqY0ol081b1TclJJv03BQeBA/YtSzQFovGFmsiOcHb7lrW3+KJxw/pQECcZOu5WqrR9gymcrjtM7q8yQlmMvolAkjJQuJfihn2BSk3xvPw6j4GhNVtPTjsGxMMxPzvadAxJwdtE8TnHTVZHxA1N+AOPMoGe0owGbERjeDMGp5bOLlFs46cASOqmEzixz/RZxqeR+Y7JFUnNdD17fdBmV4PKXqPgTsGcUJK/CQ8lqGXWuoJSMaLoaDgm28rf2D6Y5y7tOChsqv1veLQ7vt4rI8XdpN5c9zotNE7oLueTiD8S6PxF4DoRQFtGqiGriSsaMvaVtPPHtJLJ8aF/MznXF5AlLVF6DIWj0X9Sk+B43Tq2SxVRhfyLGeGeGcD8DS+NNKSxoUJgzBYejaz8+B38SyiJSr/3CR7uuYpVR6J1bKP2rbUvJeKSYMAkv+xsNO+msVtK6I1wqs1pPzVGTFyDgQ4ZWqA4KKunHerSjhprQVqAeP4Fh1u1HyeG3DFI6W2386yjtaiBQaSOjOCMXZzYOPWLnzuqZbN3BzY8kpzXvpKANxY+1FNBkATdw4NnMK5MNHS1HqjV2MR08etkrsYOS+kNRq1pK529W5EwSwuadIMePtguxZGEv
    username: AgAwZJ+WORzAWidGYf5PJlBAHora0gBgZMVLRdRuv9Km8k+nG606JuwtTG6Nnh6W6eYSIk9wSXvkpQCjwZUKDYn0Tr7+NW1QUze5jrNSiZxWB+tXpkXFjA++oFyl52eXIjGIlc5qGofmx/WG1qnxSh/vCVxlRQXXYHAdtEiCNyjKmTBi2PrlA/sYYIuwPv+N8YNrFzdfUoskiKTZpfWO/qzsqwDpkMMlu8cGLrpkA+9Xhz9e5tGKq1+QMaARu3gmUyFrUobitOSpUtWy+UQ7Bgfj+e0RUCopmtqaO8yumDYahK8uIzCHigpzrSaQH8tW/Y2FILHB/kw9703zzfrUp5aFdm2P8tzOvhngfZ3mpoKUOyZnvDc5htynssoB8S7Otva0dJlkJg69rM2mSddR7yo2j8GKj/jH5+2tVMp3llXyL/3u/ppybXHw88PldhcKRzZqXrhotaO2FzGv+ojRh3h200JoiEUUskJ/YPsdYJ51RoOEGpqveH5qyYsSpaCgy6RChIXnRVAuxqMi0h4Mh5vBFY0CvfJAWGQHl2+EJWp460inl31AS8MfeYH/O5xlX7rwYUvWX6bYnf6RjNUtbAsO7H1MH2YIK4b0SWSdUYjRaACPOwmBYAHOyYTFEfCWjmm1ogNvIs3c8WyQ6201i2zDJOsEcHf0Pxtii5zPE7eFxCX+CfqnxDgQWPHHcERZtyd+r845dmYGgew=
  template:
    metadata:
      name: nextcloud-db-creds
      namespace: default
    type: kubernetes.io/basic-auth
