apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-nfs-data-pv
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nolock
    - nfsvers=3
    - tcp
    - port=2049
    - mountport=2049
    - soft
    - timeo=30
  nfs:
    server: 192.168.2.101
    path: /
  claimRef:
    name: nextcloud-nfs-data-pvc
    namespace: default

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi
  volumeName: nextcloud-nfs-data-pv
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-core-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-sc-v2
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-cache-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-sc-v2
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-extra-config
  namespace: default
data:
  cache.config.php: |
    <?php
    $CONFIG = array(
      'cache_path' => '/var/www/html/cache',
    );

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
  namespace: default
spec:
  replicas: 2
  serviceName: nextcloud-service
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        fsGroup: 33
      containers:
      - name: nextcloud
        image: nextcloud:apache
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /status.php
            port: 80
            httpHeaders:
            - name: Host
              value: nextcloud.lebi376.me
          periodSeconds: 15
          failureThreshold: 120 # Allow 30 minutes for nextcloud to initialize
        env:
        - name: POSTGRES_DB
          value: nextclouddb
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-db-creds
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db-creds
              key: password
        - name: POSTGRES_HOST
          value: "postgres-cluster-rw.default.svc.cluster.local"
        - name: NEXTCLOUD_DATA_DIR
          value: "/var/www/html/data"
        - name: REDIS_HOST
          value: "redis.default.svc.cluster.local"
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "nextcloud.lebi376.me"
        - name: NEXTCLOUD_TRUSTED_PROXIES
          value: "10.42.0.0/16"
        - name: OVERWRITEPROTOCOL
          value: "https"
        - name: NEXTCLOUD_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-admin-creds
              key: username
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-admin-creds
              key: password
        volumeMounts:
        - name: nextcloud-core
          mountPath: /var/www/html
        - name: nextcloud-data
          mountPath: /var/www/html/data
        - name: nextcloud-cache
          mountPath: /var/www/html/cache
        - name: nextcloud-extra-config
          mountPath: /var/www/html/config/cache.config.php
          subPath: cache.config.php
      volumes:
      - name: nextcloud-core
        persistentVolumeClaim:
          claimName: nextcloud-core-pvc
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-nfs-data-pvc
      - name: nextcloud-cache
        persistentVolumeClaim:
          claimName: nextcloud-cache-pvc
      - name: nextcloud-extra-config
        configMap:
          name: nextcloud-extra-config

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: nextcloud
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - nextcloud.lebi376.me
  rules:
  - host: nextcloud.lebi376.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-service
            port:
              number: 80
