---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db-creds
  namespace: default
spec:
  encryptedData:
    password: AgAA1eBYYElVtOvP/Lif+qi0cA5an06sApDQKZtAkF4wA+wjadYhu16CnWDrdi/HvlTA/FB/6McpR2u7PkKCpL2VGwC8zYYT3lnFVhyTBcX6o3hqivyA7DMU/3pPilAdQObsgLjLGo+nGhgnhmGzxOKLAH1nXgW42n7vfr0fH6vDID0ohKyGKOjItZVjlmzXW6qWMi8m6W6hEheVgE8osZOSQ8HWz6s1tA2DR8PSV5juyQHNh86I7aVeavPJQOJCVXbSkzYqHMsmIkwwZZcCJWm7wZR8gvRg4kiLMfpUzuHz2su4q3bDLdAglVSBMKWsVUEipG4Vgoa6nphrsP7/eTEMzTjOspIPBua/FhYjwJaIS6C8ME/cXY/mrMuzct/FYgg2ekEMMI7HrI4NOVL8178s0Z93ltpggqUbfdCMHaD59O+VD68vNJK9i93DwSFxXF+lyVQnoCb4Ug9auE+oUL4RLqv7+Ll3MtKTtTF83UdrqapiTzKmsIlmhatZ1eQoAFW07QhqBTm/0xZFe/btuFiMoYsmSFNZnhlCPzY9/GQSHZeqsVnTybMEtrW7k9Tsy7Z544JA6jEkh8HqZQsGX8kjZCJreWbvKDRkattUNncFWR6f52T7lFCdj4qwRXn0vtDpVMvl2xr7nxHvAzvidD4mJoCXLCaLIg/pq4qixOV8UJrnG8XkZk4c9+DcKrcN2G5IubSCVu8M2u6+VcR87XMu
    username: AgBfrE675zgrF8sBnYvPvrA+gs1Ci0QvyL6gHJzEOqVPlGDB4kxst42m7vPkp2Jngg6KalqGz5wf2eq1JUMULfiLmJgzFbcBnM8v4Spa1xUVE4GHUuokUfcZ3VvmV7ata+pTmobmAGySPfO67fzste+IVKYwFihVwO1QT4+2Fur55Pja4XX4VX242DplPRauSnPQ8EcLICyAx/uZYFONSw+XDZZP5kyR+TXmp5Hg2oWQz0NwduhTdytZHWSxdbmysMH/QPfz9aH3Sp1SkIgdpDKaLzRe05AMulRUvjIla7vGF84Mtss080tEUvgKIvCnEPawoAM0xnQTcmCXU5TFRIfErX7vV9jzx+MI92ZW3m1k4nzlyHamyLUv3bR+3oR2S1EP0hiD7h6KupA+LO5CxmXfCevOFB4NzPqEhrC+aqpWLZ+0gk9syMf14Siisya5Kw5uX4pIq4fKwBSaVT4hij9ZJov8DWxJNYJ7PQyQc6bieIkORWQIah4lvrBm4jfR+5S4vHLB4Coh5KvSfWFYQ9PsQ45sk13KoSsBdRmYMM6RacsK50zoo9DNVCDE88rY6AJmpxEgSOsiUnLpK/VLxVtBIQ8ymQ//oGPbL2lyehD91Gx5KWd7pncj/r+q1zh/joWzc0WXWHtZUCtJwBy0Laqt4nWs2wRJYHBHCJUpRgXnr+/FzyRSWm5kaHgFn3DgzJgL3QaOR1h9cbE=
  template:
    metadata:
      name: nextcloud-db-creds
      namespace: default
    type: kubernetes.io/basic-auth
