apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-redis-config
  namespace: default
data:
  redis.config.php: |
    <?php
    $CONFIG = [
      'memcache.local'       => '\OC\Memcache\APCu',
      'memcache.distributed' => '\OC\Memcache\Redis',
      'memcache.locking'     => '\OC\Memcache\Redis',
      'redis' => [
        'host' => 'redis.default.svc.cluster.local',
        'port' => 6379,
      ],
      'session.save_handler' => 'redis',
      'session.save_path'    => 'tcp://redis.default.svc.cluster.local:6379',
    ];
