apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi
  storageClassName: hetzner-sb-nextcloud

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-core-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-sc
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:apache
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_DB
          value: nextclouddb
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: nextcloud-db-creds
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-db-creds
              key: password
        - name: POSTGRES_HOST
          value: "postgres-cluster-rw.default.svc.cluster.local"
        - name: NEXTCLOUD_DATA_DIR
          value: "/var/www/html/data"
        volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html/data
        - name: nextcloud-core
          mountPath: /var/www/html
        - name: nextcloud-redis-config
          mountPath: /var/www/html/config/redis.config.php
          subPath: redis.config.php
      volumes:
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data-pvc
      - name: nextcloud-core
        persistentVolumeClaim:
          claimName: nextcloud-core-pvc
      - name: nextcloud-redis-config
        configMap:
          name: nextcloud-redis-config

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: nextcloud
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - nextcloud.lebi376.me
  rules:
  - host: nextcloud.lebi376.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-service
            port:
              number: 80
