---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-creds
  namespace: default
spec:
  encryptedData:
    password: AgCRtoJPIlTr0Yte6etlBU/SkYviqxzW5DKWfoLb22KUn6Wmq1d7vV4DX2ZlpvMXsEPRATKTsf5V90V4gzLBULKnIqNUcgYivmwMDx+daoGmnaCczSVGLW/C8/5Bk33O8puK+wZBdGeKmbtzmQwIwbveNUNLMF6UTzS3AOMwpRAHVBu3eoEE2P+4CvKi8wNo1zAiBX8JpC8aX5Aa8mg+GwBAkeUZwbRZb2VZePLPPrqHbGuKBo+8p5JP6KJQWLWoQ3Qv6WCx0g9moifufdp8yuwrAo4zAGPixzikE0J/7RVFLOrqQZw5aDqZd/SiSHv+Vz1daFSK23yDTwzFbPlmdPwGdZizpYt9KWszRVxx/usjdYfdALCnm4Vz4S50bBQ5M3wh7gOCPHcZRZI9+G/KjhWXZ66LP0uFXqbLxnjww73wXjtcAlh2RGR44CxJLl3i0HJvZMy4s8+xTEhe+hFwlpoDgo9Gi/YLqiD6Z2rw0d8Er7rIHwxbrv+c33N6gmxB1mcXvqlbaR0xCVJFAGNeYJ8cT8PZeSU4fmN0BVjLzC/Vq2ETjWxg+NvUE9rjy5L+sD/HICdk8Kp5FxdVOFjk37GNM/zzUQViEg0I+ZWLkT7v4UAShO7FWQk0MIzuGG/bxWPqwIV4VwMrHXkR38njCPSBlldFkygXeBe3kuzovlVI26jfDR2w9fgzFdBQdGi+VbODLDEgg8TOqxoBoWBc8hiT
    username: AgBpFEuUhveFHLvpOTlVrIbt7e+8mDqLKPzh9VRahq91Rauq9a3hw1DBFKd/uI0xhdIQAv0Sg2ndI0O8PnEZcsOSRA6y4JzflFTsWiymw4HrDrLhl9fgkDKjemTC4vxPtzJYk2dSo0vsbvR5/0gVJANm7MG4WtVsQgvxUKYxgf5ZM1I8+bm/hOIjH74PzDeyDRcytPqq/adLcvstS6Iysmxu4K0nevh6f1RtKkhg3cSR7xxUvm9M6CsjQSKat7TbZEjFPmbaKn7WurmlFsPBq5bcdgSQglYSoJ1VprJJ59rldTRGNj7VqkzdNesmuR8ydAwmqAxp0z2X0/KvMFLPsF9ik37JAuL+8dHwObKrWRlZoB2qpaggeKTqAouli+Yg5jqAZyJRnqOjnndj8gqnlbbcf1DvLzrnWi9fSbL6U9SRJPt5ROwGEs0H8KzDDl1gbp3+uQHt7vezvHX+rVUdLx5B6sDr/Qa+KprHVOhtxZ9yQQ0S7MXhGduZgw9reCcd1siUulwQ7Lm9DK5fj4WhEA76GVnLi6Nq4o4e6ZUcWMIl1dROIAmelhPxvzah75bImWEm8eETHtD9ORHH8JRP1/MthFBE+wbrfH1L3vIdHU7JAgsNpNqBh263MtlFSoRJZZbCKQOxv7uAqaT/q6u5EAmGCFJLdsv8spSl3+nYtJgpXEcWWC4OLNljOQihikyIonGjmEk4ZQ==
  template:
    metadata:
      name: nextcloud-admin-creds
      namespace: default
    type: Opaque
