---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-sb-creds
  namespace: default
spec:
  encryptedData:
    configData: AgAks5Ad/80YNSqDSdbI6SEWCtXgMXkQVv6glVaIaAWtETOAAVMTHtQoew876GbBb52adcwnLjqaUyi9ByfC4SZ7TH/uMNbtGT4N05+qsaNVsSc3t7qA3uyz9VYPQMUpSjIKe34BM/FnetOqJCH4lk0+VbeRHh+oYpnKTrEgFqnSs5pM2NRRv0ueZiTaSCOrtidm3Wa0qlyIR+6VCLbwTbgsrHYIlmsts8iuK0uMEJ4OVOztieZfYdrvJ4vv46BoGtDdtt4l8FMxABhSqxhE9EuVWGWI8OmK7v2NCaCB+i8BuOhYLpVszRRDP2PAfBY1TL73HFb6oqKySI5Dr3SvkyxlNEtRmgC0JcK+trR+KnsOARpjBD+RroRupQuKy3yK9sOANhPguOJZksicnEDBX6nkLC7blvcbGapnpkh6uHxZ3iItA1fZQz9kN3G0fZBQDwo+5qCFcN8KKQlYQIrWpMxrbNrlPCezdvnWlvbE8ZyLp2za6Rx+M3hbyGaSongtBxdycbBoyRRJm5BhzgMiJYx9dpt1BFvTTLvH1vpZiDh1e/GMQzNVQ26kqCFths9YM5mSpFD9k90PJAQzDKTD/c8of9OTe0BztGVhUMnS9OHMMd+p5R/BBY5Ao+SQ+2POPR6r03VzFNafB7rqkzK78XQHvl90fkxUh+HN8Pi4CtNj46TLG3+8SwB6IHGI9mIUhe/wcl4mV6rauUHPq+GrQejL5X0Aw3Um7LA9qpzN91BGg4UJQoc4S8+tuweGlHOue6fSQNCbsK/1tBJMvubZ5TGdKaehoCqiuq4FeMhWIa6prKpk/Yc0TsHrxq3Gc+/nZOciCIeDDp3MSXmtCVsVO+AZyscGjAablwitf6UJ3Rj71oQfxASXdWfo4OwPkeaXkbIY339U2X5nelV10zfsJzx1w+mKuLxrU91J6+EaO24qkdqvvY3t0MNOPw==
  template:
    metadata:
      name: hetzner-sb-creds
      namespace: default
    type: Opaque
