---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    api-token: AgA1KCooJPN0/j653z0XgMc0qeDoENe3DDVU8ADVn06PvMnlJxyRMswj68OctwlAxBhsNmdjB2PeRyo7OtYJzxKvHGBzl1sCim9R+vrYuC/qHFbJE8btzKPE2D8Q305fZMy1wNhPWmFnaIiaegdPvVLP/S8K68W/5VmpvHYP5xUno1NtjzA3WZPzGiOaCG+fUSKreegPW0TOYiFS8CkyU1muq2UZ0Q1zDedhzfqKel56g/imVfTRsfOODsldEXdfGgNmAFeKrl3zCboCfRZCUkyaFwMLYfq1D0Rix2/5zrVCDy+tnBUDsygy0m1DnMzEcbnQ00jwPN/Ed9YG89htyF/k7dlhdmEs+1BtGhcJEHrA08X7QgKjnnOzfSSFjHe23k+cwemyKwRz8Vm4f+kIx6T/EsYypPnue+jjecGCOZfzJ7AuEdbkIxzJ6CGRirRslxSLoiqpedzpQUdPTl6N/blzjbWJnT/jaWgzZsUqkku97xIp8rCT+iiMNQXP3Ldp8P/G9ngXgZ+L9ugj602BUo8l+0h54toN8sPRDYv9uaG4hiYZ9b9LnbVGQgFLxno+5g041mWFUd5p2j7isfFs9vbLs9oOqyLZTTOYAlfRhI+BR0Pdq0k1QgNbmpdyC95uvBM/doRJCHw9TaDhLmDvx2aMgB5fBGZn+BvSb8R4Y4uAmKhE0vul07oFJ4dFSq1raD2a+4hxHWp31vVD12JN66l8ErExVJiNylATClyQkDU53T0cNq7m9S7Y
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
