---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCYAx48PZ2CiufmqwqiW77HNmg0MYrBQ1KvggxqQa5qA6QOb4G0SNLQUItoMnG/8HUm1+lsYJraEkDPE/9Uv9v7oFcvlgYP2q55ZaAxm9y9KSfeovJVTsvvWEnlb8Akk1ghKMMvwxXPwoAqvOluwDj3/j54i4PMaeixVrH+I0KhPtxda5zfiL0+7vKXunZ51ozvYMdTbqvyGHMpxmuhsdyELValZBYDToBOvqECXhISJrp6t2NzGUUW+UpSTT1Ye7lyeBY83hs6sFaKy3QGKTPVtFKqll75WiFJS7p60kN+MxyU2cdtGMqmX1ilJKRfUQQsLMEzxripouhkrNwNj4RPXYdwwYtTEHIf0km46u2Y2eB/ynetDBHPWVcE5KTuX5BPP/5K/RK7Za3c/XGqrD2UFGzvCjuIrsPVmf3h94QDfc2UtyHikvJOIuPGTDR3MQtS/2wsVfo/0xL7WhVb+u2JqFZNBvoq+eR1SidMCNMEeRLiYuXpxEiXoGcvbAuuRvOP4RPg3SYTLtZGgXRb6ewHmIN+wO8ylIGj+eLTBLDSG0Q3bu9qFuHf6k8wJUVzWS2dpcE6DOrO/tF7A8q8ZmrnwfoO9YMZm8p4Bnljw2yGwOAOj7wIq27jj6MYVfv3kAgnM4wWATGZX9nJzEh3sz9AtjBOcJA+qGKPtOWcdYdF0kqpdsEQVb8YMYdedLlE+TdL3q0SNsiNqvVphciSxn8CTpJ4G4505rkB/N64TNWyPBsgEzCKuwjM
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
