apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  defaultCertificate:
    secretName: wildcard-tls-secret
