apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cnpg
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  repo: https://cloudnative-pg.github.io/charts
  chart: cloudnative-pg
  version: "0.23.0"
  targetNamespace: cnpg-system
  createNamespace: true
