apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lebi376/kubernetes-homelab.git
    targetRevision: HEAD
    path: vaultwarden
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
